-- ============================================================
-- LOADFIT - CONFIGURAÇÃO INICIAL DO SUPABASE
-- Execute este arquivo no Supabase > SQL Editor.
--
-- IMPORTANTE:
-- As senhas NÃO ficam na tabela public.usuarios.
-- O Supabase Auth armazena e protege a senha no schema auth.
-- A tabela public.usuarios guarda somente os dados de perfil do usuário.
-- ============================================================


-- ------------------------------------------------------------
-- TABELA: USUÁRIOS / PERFIL
-- ------------------------------------------------------------
create table if not exists public.usuarios (
    id uuid primary key
        references auth.users(id) on delete cascade,
    nome text not null default '',
    email text not null default '',
    criado_em timestamptz not null default now()
);

create index if not exists usuarios_email_idx
on public.usuarios(email);

alter table public.usuarios enable row level security;

--O próprio usuário autenticado pode consultar e atualizar somente o seu perfil.
grant select, update on table public.usuarios to authenticated;

drop policy if exists "Usuario visualiza seu perfil" on public.usuarios;
drop policy if exists "Usuario altera seu perfil" on public.usuarios;

create policy "Usuario visualiza seu perfil"
on public.usuarios
for select
to authenticated
using ((select auth.uid()) = id);

create policy "Usuario altera seu perfil"
on public.usuarios
for update
to authenticated
using ((select auth.uid()) = id)
with check ((select auth.uid()) = id);


--Função executada automaticamente quando uma conta é criada no Supabase Auth.
--Ela copia o nome e o e-mail para public.usuarios.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
    insert into public.usuarios (id, nome, email)
    values (
        new.id,
        coalesce(new.raw_user_meta_data ->> 'nome', ''),
        coalesce(new.email, '')
    )
    on conflict (id) do update
    set nome = excluded.nome,
        email = excluded.email;

    return new;
end;
$$;

--Evita duplicar o trigger caso o script seja executado novamente.
drop trigger if exists on_auth_user_created on auth.users;

create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();


--Se já existirem contas criadas antes da tabela public.usuarios,
--este comando copia essas contas para a tabela de perfis.
insert into public.usuarios (id, nome, email, criado_em)
select
    id,
    coalesce(raw_user_meta_data ->> 'nome', ''),
    coalesce(email, ''),
    created_at
from auth.users
on conflict (id) do update
set nome = excluded.nome,
    email = excluded.email;


-- ------------------------------------------------------------
-- TABELA: MATERIAIS
-- ------------------------------------------------------------
create table if not exists public.materiais (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    nome text not null,
    categoria text not null,
    peso numeric(10,2) not null check (peso > 0),
    quantidade integer not null check (quantidade > 0),
    criado_em timestamptz not null default now()
);

create index if not exists materiais_user_id_idx
on public.materiais(user_id);

alter table public.materiais enable row level security;

grant select, insert, update, delete on table public.materiais to authenticated;
grant usage, select on sequence public.materiais_id_seq to authenticated;

drop policy if exists "Usuario visualiza seus materiais" on public.materiais;
drop policy if exists "Usuario cadastra seus materiais" on public.materiais;
drop policy if exists "Usuario altera seus materiais" on public.materiais;
drop policy if exists "Usuario exclui seus materiais" on public.materiais;

create policy "Usuario visualiza seus materiais"
on public.materiais
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Usuario cadastra seus materiais"
on public.materiais
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Usuario altera seus materiais"
on public.materiais
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Usuario exclui seus materiais"
on public.materiais
for delete
to authenticated
using ((select auth.uid()) = user_id);


-- ------------------------------------------------------------
-- TABELA: CAMINHÕES
-- ------------------------------------------------------------
create table if not exists public.caminhoes (
    id bigint generated by default as identity primary key,
    user_id uuid not null default auth.uid()
        references auth.users(id) on delete cascade,
    placa varchar(10) not null,
    marca text not null,
    modelo text not null,
    capacidade numeric(12,2) not null check (capacidade > 0),
    criado_em timestamptz not null default now(),
    unique (user_id, placa)
);

create index if not exists caminhoes_user_id_idx
on public.caminhoes(user_id);

alter table public.caminhoes enable row level security;

grant select, insert, update, delete on table public.caminhoes to authenticated;
grant usage, select on sequence public.caminhoes_id_seq to authenticated;

drop policy if exists "Usuario visualiza seus caminhoes" on public.caminhoes;
drop policy if exists "Usuario cadastra seus caminhoes" on public.caminhoes;
drop policy if exists "Usuario altera seus caminhoes" on public.caminhoes;
drop policy if exists "Usuario exclui seus caminhoes" on public.caminhoes;

create policy "Usuario visualiza seus caminhoes"
on public.caminhoes
for select
to authenticated
using ((select auth.uid()) = user_id);

create policy "Usuario cadastra seus caminhoes"
on public.caminhoes
for insert
to authenticated
with check ((select auth.uid()) = user_id);

create policy "Usuario altera seus caminhoes"
on public.caminhoes
for update
to authenticated
using ((select auth.uid()) = user_id)
with check ((select auth.uid()) = user_id);

create policy "Usuario exclui seus caminhoes"
on public.caminhoes
for delete
to authenticated
using ((select auth.uid()) = user_id);
